### ISSUE TITLE
Readme.md request

### ISSUE THREAD

**Issue by CharlesChiuGit** [viniciusdof/spotifyOPML#1]
Hi, I'm currently trying to export OPML from spotify, but it's seems that spotify doesn't support exort OPML natively.
It's wonder that someone create a program to do it! However, I'm not used to OPML.
If it's possible for your to add a little turtorial of this repo? It would be a great!

Thanks for your effort!

**Comment by viniciusdof** [comment]
Sorry for the delay, it's been a while since I looked at this repository.


I never actually finished this project, nor did I get to go very deep into this part, but my idea was to use some search api, like https://www.listennotes.com/api/docs/ to search by name, get the rss feed and create an OPML, I don't know if it's the best way, but it's what I had thinking at the time I started this, but as I never had time to finish it I can't tell you anything more in depth.


but in the little I've seen, there's not much to do besides using search apis to "convert" the OPML to spotify and vice versa

**Comment by viniciusdof** [comment]
the little code I have today does this so in the sense of importing, I read an OPML and look in the spotify api for shows with that name.

the idea was after that to have a confirmation step (because sometimes spotify didn't return the right podcast) and only then subscribe the user to the podcasts on spotify

**Comment by CharlesChiuGit** [comment]
Interesting! Thanks for sharing your thoughts with me. It does sounds like a good workaround with the search api. Also, thanks again for the reply!
